server:
  port: 8080
spring:
  application:
    name: rag

  ai:
    model:
      embedding: ollama
    # ==========================
    # Spring AI Chat Observability
    # ==========================
    chat:
      observations:
        log-prompt: true
        log-completion: true
    # ==========================
    # Ollama
    # ==========================
    ollama:
      base-url: http://172.26.8.66:11434
      # ==========================
      # LLM / Chat Model
      # ==========================
      chat:
        options:
          model: llama3:latest
          temperature: 0.2
      # ==========================
      # Embedding Model
      # ==========================
      embedding:
        model: mxbai-embed-large
        keep-alive: 5m
        truncate: true
    # ==========================
    # Milvus Vector Database
    # ==========================
    vectorstore:
      milvus:
        client:
          host: 172.26.8.66
          port: 19530
          username: root
          password: milvus

        database-name: default
        collection-name: documents
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE
        initialize-schema: true

app:
  rag:
    top-k: 5
    similarity-threshold: 0.75

# ==========================
# LLM Observability (Langfuse via OTel)
# ==========================
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  # Disable metrics export if you only want tracing
  otlp:
    metrics:
      export:
        enabled: false

  opentelemetry:
    resource:
      attributes:
        service.name: ${spring.application.name}
        service.version: ${APP_VERSION:0.0.1}
        deployment.environment: ${DEPLOYMENT_ENVIRONMENT:local}

    tracing:
      export:
        otlp:
          endpoint: http://172.26.8.66:3000/api/public/otel/v1/traces
          headers:
            Authorization: "Basic ${LANGFUSE_AUTH}"
            x-langfuse-ingestion-version: "4"